### ISSUE TITLE
Size of rosbags created

### ISSUE THREAD

**Issue by ihtishamaliktk** [lrse/dataset2bag#3]
Hi 
Thank you for this package, it is quite convenient. I have a query regarding the size of the rosbags created with this package. The rosbags I create are approximately double the size of original image data. The stereo image data is approx. 80 GB while the rosbag ends up to be 134GB. The only chnage to the code (regarding images) I made is to to read grayscale images and use ros.encode 'mono8'. The data is at 40Hz.
On the other hand, while checking the rosbags provided online for Kitti, their sizes are exactly the same size as the orignal stereo data. Am I doing something wrong/extra?
I have no compression here.
The rosbag info is :

```
> path:        S01.bag
> version:     2.0
> duration:    11:36s (696s)
> start:       Mar 05 2019 13:59:25.00 (1551787165.00)
> end:         Mar 05 2019 14:11:01.82 (1551787861.82)
> size:        134.6 GB
> messages:    111840
> compression: none [55921/55921 chunks]
> types:       sensor_msgs/CameraInfo [c9a58c1b0b154e0e6da7578cb991d214]
>              sensor_msgs/Image      [060021388200f6f0f447d0fcd9c64743]
> topics:      /stereo/left/camera_info    27960 msgs    : sensor_msgs/CameraInfo
>              /stereo/left/image_rect     27960 msgs    : sensor_msgs/Image     
>              /stereo/right/camera_info   27960 msgs    : sensor_msgs/CameraInfo
>              /stereo/right/image_rect    27960 msgs    : sensor_msgs/Image
>              /groundtruth_pose    	 27960 msgs    : geometry_msgs/PoseStamped
```

 The image raw information in rqt is like this:

```
header
	seq:  5660
	stamp
		secs:  1551787306
		nsecs:  59999942
	frame_id: camera_right
height:  1195
width:  2013
encoding: mono8
is_bigendian:  0
step:  2013
data:   !!#$%#%'%'$$()((**+-/0,&& !*)%(+...
```

**Comment by protobits** [comment]
If the originals are compressed (JPG or PNG, for example) the size will increase significantly in the rosbag since bags store them uncompressed. Otherwise, I do not know what could be happening. Maybe you can share the dataset2bag invocation here and I can see if there's something that looks wrong.

**Comment by ihtishamaliktk** [comment]
@v01d  You are right. Really simple thing I missed. Thank you for clearing.
When I stored the images as compressed PNGs they were exactly the size they should be.
