### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by dungali** [lrse/dataset2bag#4]
can i get sample of calibration.txt file and timestamps.txt?
i cant solve the error "what():  You need to specify a timestamps file"

**Comment by protobits** [comment]
I don't have sample file but the format is very simple, have a look at the code (the comment states the expected format):
https://github.com/lrse/dataset2bag/blob/c4fa8022ed59cf2a0e542d73878b6559669886ee/src/dataset2bag.cpp#L100

**Comment by dungali** [comment]
Im begginer in coding
If u dont mind pls advice me about timestamp.txt
I aleady checed that line, i tried several files but i dont know about how to writre in timestamp.txt

Could u kindly give me 1 sample line of timestamp.txt?
if second is 10 and nsecond is 10, what i write in?
(10 10)
10 10
<10> <10>
10.10
[10] [10]

**Comment by protobits** [comment]
The format corresponds to the second line in your example. Everything is space delimited in the inputs.
