### ISSUE TITLE
Some errors of laser scan part

### ISSUE THREAD

**Issue by WANGYINGYU** [lrse/dataset2bag#5]
Hi,

I meet some error when I use the code to generate rosbag format.

When I only use odometry and timestamps to generate the rosbag, the code can run successful. But when I add the laser data, the code print a error as below:

```
Parsing laser data...
   [                                                                                 ] 0.00%terminate called after throwing an instance of 'rosbag::BagException'
  what():  Tried to insert a message with time less than ros::TIME_MIN
Aborted (core dumped)
```

Is there something wrong with the format of the data in my laser section? My format is as follows(some parts of my laser data):

```
0.332325834416190 662 0 30 -110 110
0 0 5.932 5.9141 5.8948 5.8746 5.8541 5.8339 5.8149 5.7973 5.7815 5.7679 5.7564 5.7471 5.74 5.7351 5.7323 5.7315 5.7328 5.7359 5.7407 5.7471 5.7549 5.7639 5.7738 5.7843 5.7949 5.8054 5.8154 5.8245 5.8327 5.8397 5.8457 5.8508 5.855 5.8586 5.8618 5.8647 5.8676 5.8706 5.8739 5.8775 5.8817 5.8864 5.8919 5.8981 5.9053 5.9134 5.9226 5.9331 5.9448 5.9579 5.9727 5.9892 6.0077 6.0284 6.0516 6.0779 6.1077 6.1419 6.1818 6.2294 15.55 15.523 15.497 15.472 15.447
```
The first line is [angle_increment] [scan_count] [min_range] [max_range] [min_angle] [max_angle], angle is in degrees, the second line is the timestamps and ranges.

Can you help me @protobits? Thank you so much.

**Comment by WANGYINGYU** [comment]
I have solved the error which caused by the timestamps start with 0 second and 0 nanosecond. 

Here is the generated bag, is the bag correct?

```
path:        out.bag
version:     2.0
duration:    1:15s (75s)
start:       Dec 31 1969 16:00:00.00 (0.00)
end:         Dec 31 1969 16:01:15.00 (75.00)
size:        292.5 KB
messages:    226
compression: none [1/1 chunks]
types:       nav_msgs/Odometry     [cd5e73d190d741a2f92e81eda573aca7]
             sensor_msgs/LaserScan [90c7ef2dc6895d81024acba2ac42f369]
             tf/tfMessage          [94810edda583a504dfda3829e70d7eec]
topics:      /robot/odometry   75 msgs    : nav_msgs/Odometry    
             /scan             76 msgs    : sensor_msgs/LaserScan
             /tf               75 msgs    : tf/tfMessage

```

**Comment by protobits** [comment]
Hi, as the error message indicates, the timestamp is not valid. ros time 0.0 is a reserved value to indicate an invalid timestamp. You may get away with it (not sure how you created the rosbag in the end) but it is not recommended. I'm closing since there doesn't seem to be a bug here.

**Comment by WANGYINGYU** [comment]
> Hi, as the error message indicates, the timestamp is not valid. ros time 0.0 is a reserved value to indicate an invalid timestamp. You may get away with it (not sure how you created the rosbag in the end) but it is not recommended. I'm closing since there doesn't seem to be a bug here.

Thanks for your reply @protobits. But I think it still exists some errors. The input data of my case is 76's moment laser data and each moment include 662 beam, so the data format of the laser I used is

```
0.00290009 662 0 30 -0.95993 0.95993  %this line is parameters [angle_increment] [scan_count] [min_range] [max_range] [min_angle] [max_angle]
0 1 5.932 5.9141 5.8948 .............. % this line is the timestamps 0 1 and 662 scan ranges  
```

The odometry data include 75 data, timestamps I used start from 11 and end with 75 1 
The data  I used is 

```
1 1 0.52371 -0.031198 -0.0078041   %this line is timestamps 11 and odometry information [x,y,theta]
2 1 0.71447 0.05245 -0.010167
3 1 0.90151 -0.1274 -0.01216
```

The timestamps I set is

```
0 1  % start from 01 and end with 75 1
1 1
2 1
3 1
4 1
..............
75 1
```

Can you help me check if it exists some errors of my code or parameters? I am not sure if the parameter 'scan_count' I used is correct and if the odometry start from 11 while laser data start from 01 is correct.

Thank you so much again.

**Comment by WANGYINGYU** [comment]
Here is the information of the rosbag I generated, I think maybe it lack many data in it.

```
path:        simu.bag
version:     2.0
duration:    1:15s (75s)
start:       Dec 31 1969 16:00:00.00 (0.00)
end:         Dec 31 1969 16:01:15.00 (75.00)
size:        292.5 KB
messages:    226
compression: none [1/1 chunks]
types:       nav_msgs/Odometry     [cd5e73d190d741a2f92e81eda573aca7]
             sensor_msgs/LaserScan [90c7ef2dc6895d81024acba2ac42f369]
             tf/tfMessage          [94810edda583a504dfda3829e70d7eec]
topics:      /robot/odometry   75 msgs    : nav_msgs/Odometry    
             /scan             76 msgs    : sensor_msgs/LaserScan
             /tf               75 msgs    : tf/tfMessage
```

**Comment by protobits** [comment]
I'm not sure why you think anything is wrong. Have you tried playing it back? The rosbag info looks as expected.

**Comment by WANGYINGYU** [comment]
> I'm not sure why you think anything is wrong. Have you tried playing it back? The rosbag info looks as expected.

The reson I think it maybe exits some errors is that I used a tools provided by Cartographer to valid the generated rosbag and the information shows below:

```
cartographer_rosbag_validate -bag_filename simu_76_notme.bag 
E1227 07:01:06.066066 51494 rosbag_validate_main.cc:383] Point data (frame_id: "base_link") has a large gap, largest is 1 s, recommended is [0.0005, 0.05] s with no jitter.
I1227 07:01:06.066459 51494 rosbag_validate_main.cc:399] Time delta histogram for consecutive messages on topic "/scan" (frame_id: "base_link"):
Count: 75  Min: 1  Max: 1  Mean: 1
I1227 07:01:06.066478 51494 rosbag_validate_main.cc:399] Time delta histogram for consecutive messages on topic "/odom" (frame_id: "odom"):
Count: 75  Min: 1  Max: 1  Mean: 1
```
 It seems strange of Min: 1  Max: 1  Mean: 1. And I run Cartographer_ros using the generated rosbag and it generated a significant error output.

**Comment by protobits** [comment]
Please verify the rosbag itself directly using rosbag tool and rostopic echo, etc. I suspect this is an issue with cartographer expecting more frequent data. I cannot help you with that part.

**Comment by WANGYINGYU** [comment]
> Please verify the rosbag itself directly using rosbag tool and rostopic echo, etc. I suspect this is an issue with cartographer expecting more frequent data. I cannot help you with that part.

I try to adjust the interval time between adjacent data, I modified the data format. I use laser can every 0.05 seconds but odometry information used every 10 scan i.e. 0.5 seconds. So the scan number I used is 760 and odom I used is 75, the timestamps I set as same as scan data used (760 timestamps). 

But the code output a error:

```
Parsing laser data...
   [                                                                                 ] 0.00%terminate called after throwing an instance of 'std::runtime_error'
  what():  Invalid laser entry
Aborted (core dumped)
```
It seems some problem about timestamps in my laser.txt? But the odom data converted successfully. The different between this time and previous are I change the timestamps from 76 to 760 and scan count also from 76 to 760.

**Comment by protobits** [comment]
The "scan count" refers to how many samples a laser scan contains (ie: number of rays sensed during a scanner revolution), not to how many entries you have in the file. I think maybe that is your issue. I will change the README as it is not clear.
